export { default as Hero } from './Hero'
export { default as ServicesHighlight } from './ServicesHighlight'
export { default as AboutPreview } from './AboutPreview'
export { default as Stats } from './Stats'
export { default as Testimonials } from './Testimonials'
export { default as Clients } from './Clients'